### ISSUE TITLE
Several Features Not Working

### ISSUE THREAD

**Issue by nenghaoooz** [fieryhenry/Battle-Cats-Save-File-Editor#3]
I tried using some of the features in the save editor but it seems that only the xp, cat food, get a specific cat seems to work. 

Regarding materials, once I input my desired values, it changes inside the game to random strings of value and I can't build anymore.

I'm sorry I'm not a developer or anything so I don't know how to generate any data for you to improve on it. Several of the option have their own error message and then it automatically closes down, so I couldn't even copy paste haha.

Still, I love the idea behind editing the save file. Looking forward to new updates/fixes! :)

**Comment by fieryhenry** [comment]
Yeah the way I edit specific values in the save is that I search for values around the value to be edited to see if they match specific amounts and if they do then the editor found the specific address tied to that value and can set it to an inputed amount - because save files are offset randomly so address 5252 in one save file could be 6421 so we need to do that method. The issue is I only used a couple saves to determine if the values around the value to be edited are the same so the editor might not find that address so when it scans through the save searching it reaches the end of the file without changing anything and you get an error causing it to crash. And the building mats i'll investigate why that does that.

**Comment by fieryhenry** [comment]
All features should now work
